'use client'

import { useState } from 'react'
import { motion } from 'framer-motion'
import { Wand2, ArrowRight, Check, Sparkles, Eye, Globe, BarChart3, Target, TrendingUp, FormInput, Palette, Zap } from 'lucide-react'
import Link from 'next/link'
import MobileNavigation from '@/components/MobileNavigation'

export default function HomePage() {
  const [activeFeature, setActiveFeature] = useState(0)

  const features = [
    {
      icon: <Wand2 className="w-8 h-8" />,
      title: 'AI-Powered Question Generation',
      description: 'Our AI analyzes your content type and description to automatically generate the most relevant questions for your lead generation forms.',
      color: 'from-n60-500 to-n60-600'
    },
    {
      icon: <Globe className="w-8 h-8" />,
      title: 'Landing Page Builder',
      description: 'Create beautiful, conversion-optimized landing pages with our drag-and-drop builder. Customize colors, fonts, and layouts to match your brand.',
      color: 'from-n60-600 to-n60-700'
    },
    {
      icon: <Sparkles className="w-8 h-8" />,
      title: 'AI Content Generation',
      description: 'Get personalized insights, recommendations, and next steps generated by AI based on form responses. Deliver real value to your leads.',
      color: 'from-n60-700 to-n60-800'
    }
  ]

  const benefits = [
    'Increase form completion rates by 300%',
    'Generate qualified leads with AI-powered questions',
    'Create professional landing pages in minutes',
    'Deliver personalized content automatically',
    'Save hours on form and content creation',
    'Improve conversion rates with smart optimization'
  ]

  const aiContentExample = {
    title: 'AI Readiness Assessment Report',
    summary: 'Based on your responses, your organization shows moderate readiness for AI implementation with strong potential in process automation.',
    insights: [
      'Your team has basic automation experience',
      'Data infrastructure is partially ready',
      'Leadership shows strong support for transformation'
    ],
    recommendations: [
      'Invest in AI skills training',
      'Implement data governance framework',
      'Start with pilot projects'
    ]
  }

  return (
    <div className="min-h-screen bg-charcoal-900 text-white">
      {/* Navigation */}
      <nav className="bg-charcoal-800/90 backdrop-blur-md border-b border-charcoal-700">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="flex justify-between items-center h-16">
            <div className="flex items-center space-x-2">
              <Wand2 className="w-8 h-8 text-n60-500" />
              <span className="text-xl font-bold text-white">Formulate</span>
            </div>
            <div className="hidden lg:flex items-center space-x-4">
              <Link href="/demo" className="text-charcoal-300 hover:text-white transition-colors">
                Demo
              </Link>
              <Link href="/wizard" className="btn-secondary">
                Try It Now
              </Link>
              <Link href="/builder" className="btn-primary">
                Landing Page Builder
              </Link>
            </div>
            <MobileNavigation currentPage="/" />
          </div>
        </div>
      </nav>

      {/* Hero Section */}
      <section className="pt-20 pb-16 px-4 sm:px-6 lg:px-8">
        <div className="max-w-7xl mx-auto text-center">
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.6 }}
          >
            <div className="inline-flex items-center space-x-2 bg-n60-100 text-n60-700 px-4 py-2 rounded-full text-sm font-medium mb-6">
              <Sparkles className="w-4 h-4" />
              <span>AI-Powered Form & Landing Page Creation</span>
            </div>
            
            <h1 className="text-4xl sm:text-5xl md:text-6xl font-bold text-white mb-6">
              Create Forms That
              <span className="text-n60-500 block">Actually Convert</span>
            </h1>
            <p className="text-lg sm:text-xl text-charcoal-300 mb-8 max-w-3xl mx-auto">
              Formulate uses AI to generate the perfect questions for your lead generation forms, 
              then helps you build beautiful landing pages that turn visitors into customers.
            </p>
            
            <div className="flex flex-col sm:flex-row gap-4 justify-center">
              <Link href="/wizard" className="btn-primary text-lg px-8 py-4">
                Start Creating
                <ArrowRight className="w-5 h-5 ml-2" />
              </Link>
              <Link href="/demo" className="btn-secondary text-lg px-8 py-4">
                See Demo
              </Link>
            </div>
          </motion.div>
        </div>
      </section>

      {/* Features Section */}
      <section className="py-16 px-4 sm:px-6 lg:px-8">
        <div className="max-w-7xl mx-auto">
          <div className="text-center mb-12">
            <h2 className="text-3xl font-bold text-white mb-4">
              Everything You Need to Generate More Leads
            </h2>
            <p className="text-lg text-charcoal-300 max-w-2xl mx-auto">
              From AI-powered question generation to professional landing page creation, 
              Formulate gives you the tools to build high-converting lead generation systems.
            </p>
          </div>

          <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
            {features.map((feature, index) => (
              <motion.div
                key={index}
                initial={{ opacity: 0, y: 20 }}
                whileInView={{ opacity: 1, y: 0 }}
                transition={{ duration: 0.6, delay: index * 0.2 }}
                className="relative group"
              >
                <div className="bg-charcoal-800 rounded-2xl p-8 shadow-lg hover:shadow-xl transition-all duration-300 transform hover:-translate-y-2 border border-charcoal-700">
                  <div className={`w-16 h-16 bg-gradient-to-r ${feature.color} rounded-2xl flex items-center justify-center text-white mb-6 group-hover:scale-110 transition-transform duration-300`}>
                    {feature.icon}
                  </div>
                  <h3 className="text-xl font-bold text-white mb-4">
                    {feature.title}
                  </h3>
                  <p className="text-charcoal-300 leading-relaxed">
                    {feature.description}
                  </p>
                </div>
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      {/* Interactive Demo Section */}
      <section className="py-16 px-4 sm:px-6 lg:px-8 bg-charcoal-800">
        <div className="max-w-6xl mx-auto">
          <div className="grid grid-cols-1 lg:grid-cols-2 gap-12 items-center">
            <div>
              <h2 className="text-3xl font-bold text-white mb-6">
                See AI in Action
              </h2>
              <p className="text-lg text-charcoal-300 mb-8">
                Watch how our AI generates the perfect questions for your content type, 
                then see the landing page preview with form integration.
              </p>
              
              <div className="space-y-4">
                <div className="flex items-center space-x-3">
                  <div className="w-8 h-8 bg-n60-100 rounded-full flex items-center justify-center">
                    <FormInput className="w-4 h-4 text-n60-600" />
                  </div>
                  <span className="text-charcoal-300">AI generates relevant questions</span>
                </div>
                <div className="flex items-center space-x-3">
                  <div className="w-8 h-8 bg-n60-100 rounded-full flex items-center justify-center">
                    <Palette className="w-4 h-4 text-n60-600" />
                  </div>
                  <span className="text-charcoal-300">Build beautiful landing pages</span>
                </div>
                <div className="flex items-center space-x-3">
                  <div className="w-8 h-8 bg-n60-100 rounded-full flex items-center justify-center">
                    <Sparkles className="w-4 h-4 text-n60-600" />
                  </div>
                  <span className="text-charcoal-300">Get AI-generated content</span>
                </div>
              </div>

              <div className="mt-8 space-y-3">
                <Link href="/demo" className="btn-primary w-full sm:w-auto">
                  Try Interactive Demo
                </Link>
                <Link href="/builder" className="btn-secondary w-full sm:w-auto block sm:inline-block">
                  View Landing Page Builder
                </Link>
              </div>
            </div>

            <div className="relative">
              <div className="bg-gradient-to-br from-n60-50 to-charcoal-700 rounded-2xl p-8 border border-n60-200">
                <div className="flex items-center space-x-3 mb-6">
                  <Sparkles className="w-6 h-6 text-n60-600" />
                  <h3 className="text-lg font-semibold text-n60-800">AI Content Preview</h3>
                </div>
                
                <div className="space-y-4">
                  <div>
                    <h4 className="font-medium text-charcoal-900 mb-2">{aiContentExample.title}</h4>
                    <p className="text-sm text-charcoal-700">{aiContentExample.summary}</p>
                  </div>
                  
                  <div>
                    <h5 className="font-medium text-charcoal-900 mb-2">Key Insights</h5>
                    <ul className="space-y-1">
                      {aiContentExample.insights.map((insight, index) => (
                        <li key={index} className="text-sm text-charcoal-700 flex items-start space-x-2">
                          <div className="w-1.5 h-1.5 bg-n60-500 rounded-full mt-2 flex-shrink-0"></div>
                          <span>{insight}</span>
                        </li>
                      ))}
                    </ul>
                  </div>
                  
                  <div>
                    <h5 className="font-medium text-charcoal-900 mb-2">Recommendations</h5>
                    <ul className="space-y-1">
                      {aiContentExample.recommendations.map((rec, index) => (
                        <li key={index} className="text-sm text-charcoal-700 flex items-start space-x-2">
                          <div className="w-1.5 h-1.5 bg-n60-500 rounded-full mt-2 flex-shrink-0"></div>
                          <span>{rec}</span>
                        </li>
                      ))}
                    </ul>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* Benefits Section */}
      <section className="py-16 px-4 sm:px-6 lg:px-8">
        <div className="max-w-4xl mx-auto">
          <div className="text-center mb-12">
            <h2 className="text-3xl font-bold text-white mb-4">
              Why Choose Formulate?
            </h2>
            <p className="text-lg text-charcoal-300">
              Join thousands of businesses using AI to create better forms and landing pages
            </p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            {benefits.map((benefit, index) => (
              <motion.div
                key={index}
                initial={{ opacity: 0, x: -20 }}
                whileInView={{ opacity: 1, x: 0 }}
                transition={{ duration: 0.6, delay: index * 0.1 }}
                className="flex items-center space-x-3"
              >
                <div className="w-6 h-6 bg-n60-100 rounded-full flex items-center justify-center flex-shrink-0">
                  <Check className="w-4 h-4 text-n60-600" />
                </div>
                <span className="text-charcoal-300">{benefit}</span>
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      {/* CTA Section */}
      <section className="py-16 px-4 sm:px-6 lg:px-8">
        <div className="max-w-4xl mx-auto text-center">
          <motion.div
            initial={{ opacity: 0, scale: 0.95 }}
            whileInView={{ opacity: 1, scale: 1 }}
            transition={{ duration: 0.6 }}
            className="card bg-gradient-to-r from-n60-600 to-n60-700 text-white border border-n60-500"
          >
            <h2 className="text-3xl font-bold mb-4">
              Ready to Transform Your Lead Generation?
            </h2>
            <p className="text-n60-100 mb-8">
              Start creating AI-powered forms and landing pages that actually convert visitors into customers.
            </p>
            <div className="flex flex-col sm:flex-row gap-4 justify-center">
              <Link href="/wizard" className="bg-white text-n60-600 hover:bg-n60-50 font-medium py-3 px-8 rounded-lg transition-colors duration-200">
                Start Creating Now
              </Link>
              <Link href="/demo" className="border border-white/30 text-white hover:bg-white/10 font-medium py-3 px-8 rounded-lg transition-colors duration-200">
                Watch Demo
              </Link>
            </div>
          </motion.div>
        </div>
      </section>
    </div>
  )
}
