'use client'

import { useState } from 'react'
import { motion } from 'framer-motion'
import { Wand2, ArrowRight, Check, Sparkles, Eye, Globe, BarChart3, Target, TrendingUp, FormInput, Palette, Zap, BookOpen, CheckCircle } from 'lucide-react'
import Link from 'next/link'
import MobileNavigation from '@/components/MobileNavigation'

export default function HomePage() {
  const [activeFeature, setActiveFeature] = useState(0)

  const features = [
    {
      icon: <Wand2 className="w-8 h-8" />,
      title: 'AI-Powered Question Generation',
      description: 'Our AI analyzes your content type and description to automatically generate the most relevant questions for your lead generation forms.',
      color: 'from-n60-500 to-n60-600'
    },
    {
      icon: <Globe className="w-8 h-8" />,
      title: 'Landing Page Builder',
      description: 'Create beautiful, conversion-optimized landing pages with our drag-and-drop builder. Customize colors, fonts, and layouts to match your brand.',
      color: 'from-n60-600 to-n60-700'
    },
    {
      icon: <Sparkles className="w-8 h-8" />,
      title: 'AI Content Generation',
      description: 'Get personalized insights, recommendations, and next steps generated by AI based on form responses. Deliver real value to your leads.',
      color: 'from-n60-700 to-n60-800'
    }
  ]

  const benefits = [
    'Increase form completion rates by 300%',
    'Generate qualified leads with AI-powered questions',
    'Create professional landing pages in minutes',
    'Deliver personalized content automatically',
    'Save hours on form and content creation',
    'Improve conversion rates with smart optimization'
  ]

  const aiContentExample = {
    title: 'AI Readiness Assessment Report',
    summary: 'Based on your responses, your organization shows moderate readiness for AI implementation with strong potential in process automation.',
    insights: [
      'Your team has basic automation experience',
      'Data infrastructure is partially ready',
      'Leadership shows strong support for transformation'
    ],
    recommendations: [
      'Invest in AI skills training',
      'Implement data governance framework',
      'Start with pilot projects'
    ]
  }

  return (
    <div className="min-h-screen bg-gradient-to-br from-charcoal-50 via-white to-charcoal-50">
      {/* Hero Section */}
      <div className="min-h-screen bg-n60-800 text-white">
        <nav className="bg-n60-800/90 backdrop-blur-md border-b border-n60-700">
          <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
            <div className="flex justify-between items-center h-16">
              <div className="flex items-center space-x-3">
                <BookOpen className="w-8 h-8 text-white" />
                <h1 className="text-xl font-bold text-white">Formulate</h1>
              </div>
              <div className="hidden md:flex items-center space-x-6">
                <Link href="/builder" className="text-white hover:text-n60-100 transition-colors">
                  Builder
                </Link>
                <Link href="/wizard" className="text-white hover:text-n60-100 transition-colors">
                  Wizard
                </Link>
                <Link href="/demo" className="text-white hover:text-n60-100 transition-colors">
                  Demo
                </Link>
                <Link href="/product-guide-demo" className="text-white hover:text-n60-100 transition-colors">
                  Product Guide Demo
                </Link>
              </div>
            </div>
          </div>
        </nav>

        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 pt-20 pb-16">
          <div className="text-center">
            <h1 className="text-4xl md:text-6xl font-bold mb-6">
              AI-Powered Landing Pages
            </h1>
            <p className="text-xl md:text-2xl text-n60-100 mb-8 max-w-3xl mx-auto">
              Create stunning, conversion-optimized landing pages in minutes with our AI-driven platform
            </p>
            <div className="flex flex-col sm:flex-row gap-4 justify-center">
              <Link 
                href="/builder"
                className="bg-white text-n60-800 hover:bg-n60-50 font-bold py-4 px-8 rounded-lg text-lg transition-colors duration-200 flex items-center justify-center space-x-2"
              >
                <span>Start Building</span>
                <ArrowRight className="w-5 h-5" />
              </Link>
              <Link 
                href="/demo"
                className="border-2 border-white text-white hover:bg-white hover:text-n60-800 font-bold py-4 px-8 rounded-lg text-lg transition-colors duration-200"
              >
                View Demo
              </Link>
            </div>
          </div>
        </div>
      </div>

      {/* Features Section */}
      <section className="py-16 px-4 sm:px-6 lg:px-8">
        <div className="max-w-7xl mx-auto">
          <div className="text-center mb-12">
            <h2 className="text-3xl md:text-4xl font-bold text-n60-800 mb-4">
              Everything You Need to Create High-Converting Landing Pages
            </h2>
            <p className="text-xl text-charcoal-600 max-w-2xl mx-auto">
              From AI-powered content generation to advanced analytics, we've got you covered
            </p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
            {/* Feature 1 */}
            <div className="bg-n60-800 rounded-2xl p-8 shadow-lg hover:shadow-xl transition-all duration-300 transform hover:-translate-y-2 border border-n60-700">
              <div className="w-16 h-16 bg-white rounded-xl flex items-center justify-center mb-6">
                <Wand2 className="w-8 h-8 text-n60-800" />
              </div>
              <h3 className="text-xl font-bold text-white mb-4">AI Content Generation</h3>
              <p className="text-n60-100">
                Generate compelling copy, headlines, and CTAs that convert visitors into customers
              </p>
            </div>

            {/* Feature 2 */}
            <div className="bg-white rounded-2xl p-8 shadow-lg hover:shadow-xl transition-all duration-300 transform hover:-translate-y-2 border border-charcoal-200">
              <div className="w-16 h-16 bg-n60-800 rounded-xl flex items-center justify-center mb-6">
                <Palette className="w-8 h-8 text-white" />
              </div>
              <h3 className="text-xl font-bold text-n60-800 mb-4">Smart Design Templates</h3>
              <p className="text-charcoal-600">
                Choose from hundreds of professionally designed templates optimized for conversion
              </p>
            </div>

            {/* Feature 3 */}
            <div className="bg-white rounded-2xl p-8 shadow-lg hover:shadow-xl transition-all duration-300 transform hover:-translate-y-2 border border-charcoal-200">
              <div className="w-16 h-16 bg-n60-800 rounded-xl flex items-center justify-center mb-6">
                <BarChart3 className="w-8 h-8 text-white" />
              </div>
              <h3 className="text-xl font-bold text-n60-800 mb-4">Advanced Analytics</h3>
              <p className="text-charcoal-600">
                Track performance, A/B test variations, and optimize for better results
              </p>
            </div>
          </div>
        </div>
      </section>

      {/* AI Content Example Section */}
      <section className="py-16 px-4 sm:px-6 lg:px-8 bg-n60-800">
        <div className="max-w-6xl mx-auto">
          <div className="text-center mb-12">
            <h2 className="text-3xl md:text-4xl font-bold text-white mb-4">
              See AI Content Generation in Action
            </h2>
            <p className="text-xl text-n60-100 max-w-2xl mx-auto">
              Here's an example of AI-generated content for a SaaS landing page
            </p>
          </div>

          <div className="bg-white rounded-2xl p-8 shadow-xl">
            <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
              <div>
                <h4 className="font-medium text-n60-800 mb-2">{aiContentExample.title}</h4>
                <p className="text-charcoal-600 mb-4">{aiContentExample.summary}</p>
                
                <h5 className="font-medium text-n60-800 mb-2">Key Insights</h5>
                <ul className="space-y-2 text-charcoal-600">
                  {aiContentExample.insights.map((insight, index) => (
                    <li key={index} className="flex items-start">
                      <CheckCircle className="w-5 h-5 text-secondary-500 mr-2 mt-0.5 flex-shrink-0" />
                      {insight}
                    </li>
                  ))}
                </ul>
              </div>
              
              <div>
                <h5 className="font-medium text-n60-800 mb-2">Recommendations</h5>
                <ul className="space-y-2 text-charcoal-600">
                  {aiContentExample.recommendations.map((rec, index) => (
                    <li key={index} className="flex items-start">
                      <ArrowRight className="w-5 h-5 text-secondary-500 mr-2 mt-0.5 flex-shrink-0" />
                      {rec}
                    </li>
                  ))}
                </ul>
              </div>
            </div>
          </div>
        </div>
      </section>
    </div>
  )
}
